title: Zhane Bennett
email: zhanebennett@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Learn more about me here!
author: Zhane Bennett
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zhaben.github.io" # the base hostname & protocol for your site, e.g. http://example.com

#Social Profiles
linkedin_username: zhanebennett
github_username:  zhaben

#Site Features
disqus:
  shortname: zhaben
google_analytics: 'UA-135520235-1'

#Paypal
donations:
  paypal:
    text:           Donate      # Button text
    #id:               # PayPal button ID

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
