title:             Zhane Bennett
email:             zhanebennett@gmail.com
description:       Learn more about me here!
author:            Zhane Bennett
baseurl:           ""
url:               "http://zhaben.github.io"

# Social Profiles
#twitter_username:  
#facebook_username:
github_username:   zhaben
linkedin_username: zhanebennett

#Comments and Analytics
disqus:
  shortname: zhaben
google_analytics: 'UA-135520235-1'

#Paypal
donations:
  paypal:
    text:           Donate      # Button text
    #id:               # PayPal button ID

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
